blank_issues_enabled: false
contact_links:
  - name: Support Question
    url: https://discord.gg/GET4DVk
    about: Any questions or support needed with my cogs. Send a message in \#support_othercogs
